name = "luana-vendas"
compatibility_date = "2026-05-18"

pages_build_output_dir = "."

d1_databases = [
  { binding = "DB", database_name = "eventos_luana", database_id = "83659664-d185-4936-b77f-0721f4962f3a" }
]
